# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu-test"
  # Set a local private network IP address.
  # See http://en.wikipedia.org/wiki/Private_network for explanation
  # You can use the following IP ranges:
  #   10.0.0.1    - 10.255.255.254
  #   172.16.0.1  - 172.31.255.254
  #   192.168.0.1 - 192.168.255.254
  config.vm.network :private_network, ip: "192.168.22.20"
  config.vm.network :forwarded_port, guest: 80, host: 8000

  # Enable agent forwarding over SSH connections
  config.ssh.forward_agent = true

  # If using VirtualBox
  config.vm.provider :virtualbox do |vb|

    vb.name = "ubuntu-apache"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]

  end

  config.vm.provision "shell", path: "setup.sh"

end
