# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu"
  config.vm.box_url = "file://../ubuntu.box"

  config.vm.network :private_network, ip: "192.168.22.20"
  config.vm.network :forwarded_port, guest: 80, host: 8020

  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|

    vb.name = "ubuntu-apache"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]

  end

  config.vm.provision "shell", path: "setup-apache.sh"
  config.vm.provision "shell", path: "setup-php.sh"


end
